### ISSUE TITLE
extract submodel Error: RippleGeopackageSubsetter.add_intermediate_river_reaches() missing 1 required positional argument: 'xs_us_reach'

### ISSUE THREAD

**Issue by efdubya4** [Dewberry/ripple1d#208]
- [ ] Error 1: ```RippleGeopackageSubsetter.add_intermediate_river_reaches() missing 1 required positional argument: 'xs_us_reach'```

Traceback: ```Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 515, in extract_submodel
    rgs.write_ripple_gpkg(task_id=task_id)
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ripple1d_logger.py", line 23, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 167, in write_ripple_gpkg
    for layer, gdf in self.subset_gdfs.items():
                      ^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 130, in subset_gdfs
    ripple_xs, ripple_structure, ripple_river = self.process_as_multiple_ras_reach()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 380, in process_as_multiple_ras_reach
    xs_us_reach = self.add_intermediate_river_reaches()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RippleGeopackageSubsetter.add_intermediate_river_reaches() missing 1 required positional argument: 'xs_us_reach'```
Affected Id: ```10431976, 10432006```

**Comment by ar-siddiqui** [comment]
@mdeshotel Can you confirm if this is resolved.

**Comment by sclaw** [comment]
This has been resolved with Commit 9b0e0e8
