### ISSUE TITLE
run_incremental_normal_depth Error:  Unable to synchronously open file

### ISSUE THREAD

**Issue by efdubya4** [Dewberry/ripple1d#209]
- [ ] Error 1: ``` FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'Z:\collections\mip_05120114\submodels\10431946\10431946.p01.hdf', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)```

Traceback: ```Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\ras_run.py", line 101, in run_incremental_normal_depth
    flows, _, _ = determine_flow_increments(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\ras_run.py", line 239, in determine_flow_increments
    flow, depth, _ = get_flow_depth_arrays(rm, river, reach, river_station, thalweg)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\ras_run.py", line 207, in get_flow_depth_arrays
    wses, flows = rm.plan.read_rating_curves()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ras.py", line 810, in read_rating_curves
    with h5py.File(self.hdf_file) as hdf:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'Z:\collections\mip_05120114\submodels\10431946\10431946.p01.hdf', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)```

Affected Id:```10431946, 10431950, 10431956, 10431974, 10432158, 10432166, 10432210, 10432222```

**Comment by ar-siddiqui** [comment]
Data for this one is moved to s3://****/ripple/deprecated/0.6.x/

**Comment by sclaw** [comment]
The actual issue here is that the sub model has a cross-section with a 0 downstream reach length:
![image](https://github.com/user-attachments/assets/4cab5155-1c04-4e1c-9801-d10cd5cd8a90)

This issue has not been resolved, but it is too large to tackle in this milestone.

**Comment by ar-siddiqui** [comment]
Probably a model quality metric?

**Comment by sclaw** [comment]
@mdeshotel When you submit your model quality PR, can you have it close this issue?

**Comment by ar-siddiqui** [comment]
0.8.0 will have a model quality metric for it, but we also need to raise the error in the `extract_submodel`(?) step.
