### ISSUE TITLE
run_known_wse Errors: cannot find conflation file & KeyError

### ISSUE THREAD

**Issue by efdubya4** [Dewberry/ripple1d#210]
- [ ] Error 1: ```FileNotFoundError: cannot find conflation file Z:\collections\mip_05120114\submodels\10432006\10432006.ripple1d.json, please ensure file exists```
Traceback: ``` Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\ras_run.py", line 146, in run_known_wse
    raise FileNotFoundError(f"cannot find conflation file {nwm_rm.conflation_file}, please ensure file exists")
FileNotFoundError: cannot find conflation file Z:\collections\mip_05120114\submodels\10432006\10432006.ripple1d.json, please ensure file exists```

Affected Id:``` 10432006, 10436070```

- [ ] Error 2: ```KeyError:'10432210_nd'```

TraceBack: ```Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\ras_run.py", line 157, in run_known_wse
    rm.plan = rm.plans[f"{nwm_rm.model_name}_nd"]
              ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '10432210_nd'```

Affected Id: ```10432210, 10432222```

**Comment by ar-siddiqui** [comment]
These errors are caused by file not being present from an earlier step. Not actual bugs.
