### ISSUE TITLE
create_fim_lib Errors: KeyError & FileNotFoundError

### ISSUE THREAD

**Issue by efdubya4** [Dewberry/ripple1d#211]
- [ ] Error 1: KeyError:'10431946_nd'
Traceback: ```Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\fim_lib.py", line 182, in create_fim_lib
    zero_depth_to_sqlite(
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\utils\sqlite_utils.py", line 77, in zero_depth_to_sqlite
    rm.plan = rm.plans[plan_name]
              ~~~~~~~~^^^^^^^^^^^
KeyError: '10431946_nd'```

Affected Id: ```10431946, 10431950, 10431956, 10431974, 10432158, 10432166, 10432210, 10432222```

- [ ] Error 2: ```FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\collections\\mip_05120114\\submodels\\10431976\\10431976.ripple1d.json'```
Traceback: ```Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\api\tasks.py", line 211, in _process
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\ops\fim_lib.py", line 150, in create_fim_lib
    crs=nwm_rm.crs,
        ^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\data_model.py", line 299, in crs
    return self.ripple1d_parameters["crs"]
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_6_1\Lib\site-packages\ripple1d\data_model.py", line 331, in ripple1d_parameters
    with open(self.conflation_file, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\collections\\mip_05120114\\submodels\\10431976\\10431976.ripple1d.json'```

Affected Id: ```10431976, 10432006, 10436070, 10436160```

**Comment by ar-siddiqui** [comment]
These errors are caused by files not being present from an earlier steps, not an error.
