### ISSUE TITLE
Analyze production logs

### ISSUE THREAD

**Issue by slawler** [Dewberry/ripple1d#268]
Review output from fim30 production to identify common and not-so-common issues for review. This will include reviewing log files and  reading errors from report.

**Comment by ar-siddiqui** [comment]
Zip file of all collections error Excel was sent to @slawler.
We need to identify unique errors and file issues to GitHub

**Comment by ar-siddiqui** [comment]
Please confirm that https://github.com/Dewberry/ripple1d/issues/209 is still relevant.

**Comment by slawler** [comment]
[errors_0_7_0.zip](https://github.com/user-attachments/files/18040794/errors_0_7_0.zip)

**Comment by sclaw** [comment]
A list of grouped similar errors is available in this excel sheet: [grouped_errors_0_7_0.xlsx](https://github.com/user-attachments/files/18152999/grouped_errors_0_7_0.xlsx)

65% of the errors were contained in the top 5 common errors, and 94% of the errors were contained in the top 10 errors.

Shown below is an example for each of the top 10 errors.

Rank: 1
Occurrences: 1823
example collection: mip_04050001

`
Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 62, in <module>
    r = execute_endpoint(sys.argv[1], sys.argv[2])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 41, in execute_endpoint
    return func_lookup[func](**json.loads(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops\fim_lib.py", line 127, in create_rating_curves_db
    rm = RasManager(
         ^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ras.py", line 148, in __init__
    self.ras_project = RasProject(ras_text_file_path, new_file=new_project)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ras.py", line 476, in __init__
    super().__init__(ras_text_file_path, new_file)
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ras.py", line 427, in __init__
    raise FileNotFoundError(f"could not find {ras_text_file_path}")
FileNotFoundError: could not find C:\collections\mip_04050001\submodels\12261180\12261180.prj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 65, in <module>
    raise SystemError(f"Exception occurred: {e}")
SystemError: Exception occurred: could not find C:\collections\mip_04050001\submodels\12261180\12261180.prj
`
***

Rank: 2
Occurrences: 1820
example collection: mip_17010204

`
ERROR 4: C:\collections\mip_17010204\submodels\22937014\Terrain\22937014.vrt: No such file or directory

Unhandled Exception: System.Exception: Dataset: C:\collections\mip_17010204\submodels\22937014\Terrain\22937014.vrt could not be opened: C:\collections\mip_17010204\submodels\22937014\Terrain\22937014.vrt: No such file or directory
   at Geospatial.GDALAssist.GDALRaster..ctor(String filename, Access fileAccess)
   at Geospatial.GDALAssist.GDALRaster.ReadCurrentHistogram(String filename, Double& Min, Double& Max, Int32[]& Buckets, ProgressReporter reporter)
   at RasMapperLib.InterpolatedLayer.GetVRTHistogram(String vrtFilename, ProgressReporter reporter)
   at RasMapperLib.InterpolatedLayer.CreateVRT(String[] filenames, String vrtFilename, ProgressReporter reporter)
   at RasMapperLib.TerrainComputable.Run(ProgressReporter reporter)
   at RasProcess.CreateTerrainCommand.ExecuteWith(Dictionary`2 kvpArgs, List`1 otherArgs, ProgressReporter prog)
   at RasProcess.Program.Main(String[] args)
Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 62, in <module>
    r = execute_endpoint(sys.argv[1], sys.argv[2])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 41, in execute_endpoint
    return func_lookup[func](**json.loads(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops\ras_terrain.py", line 152, in create_ras_terrain
    result = create_terrain(
             ^^^^^^^^^^^^^^^
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ras.py", line 1398, in create_terrain
    subprocess.check_call(subproc_args, cwd=exe_parent_dir, stdout=subprocess.DEVNULL)
  File "C:\Program Files\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\HEC\\HEC-RAS\\6.3.1\\RasProcess.exe', 'CreateTerrain', 'units=Meters', 'stitch=true', 'prj=C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\projection.prj', 'out=C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\22937014', 'C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\seamless_3dep_dem_3m_5070.tif']' returned non-zero exit status 3762504530.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 65, in <module>
    raise SystemError(f"Exception occurred: {e}")
SystemError: Exception occurred: Command '['C:\\Program Files (x86)\\HEC\\HEC-RAS\\6.3.1\\RasProcess.exe', 'CreateTerrain', 'units=Meters', 'stitch=true', 'prj=C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\projection.prj', 'out=C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\22937014', 'C:\\collections\\mip_17010204\\submodels\\22937014\\Terrain\\seamless_3dep_dem_3m_5070.tif']' returned non-zero exit status 3762504530.
`

***

Rank: 3
Occurrences:  1473
example collection: mip_03130002


`
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 62, in <module>
    r = execute_endpoint(sys.argv[1], sys.argv[2])
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 41, in execute_endpoint
    return func_lookup[func](**json.loads(args))
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops\fim_lib.py", line 143, in create_rating_curves_db
    missing_grids = find_missing_grids(rm, f"{nwm_rm.model_name}_{plan}")
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops\fim_lib.py", line 180, in find_missing_grids
    terrain_part = os.path.basename(glob.glob(terrain_dir + "\\*.tif")[0]).split(".")[-2]
  File "C:\venvs\ripple1d_0_7_0\Lib\site-packages\ripple1d\ops/endpoints.py", line 65, in <module>
    raise SystemError(f"Exception occurred: {e}")
`

**Comment by sclaw** [comment]
Rank 1 above is an artifact of the production pipeline.  The true source of the error is in the create_ras_terrain step.  1,821 of the rank 1 errors had previously failed on create_ras_terrain, but when the create_irating_curves_db step was run, the error was caught again.

![image](https://github.com/user-attachments/assets/4ab7cba1-ffb8-47c9-8194-a02a6c2db57c)

Counts of each pattern of failures for the 1,823 occurrences.  With the same ordering as the above image.
![image](https://github.com/user-attachments/assets/17dbe22c-6678-4b14-aff8-02ba196eb549)

**Comment by sclaw** [comment]
The rank 2 error above occurs when the downloaded terrain is all nodata values.  When I re-ran the failing models with USGS 1/3 arcsecond DEMs (https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/13/TIFF/USGS_Seamless_DEM_13.vrt), the downloaded raster data was valid, and the models completed the create_ras_terrain step succesfully.  Note: I only tried this for a sample of 20 models.

**Comment by ar-siddiqui** [comment]
> The rank 2 error above occurs when the downloaded terrain is all nodata values. When I re-ran the failing models with USGS 1/3 arcsecond DEMs (https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/13/TIFF/USGS_Seamless_DEM_13.vrt), the downloaded raster data was valid, and the models completed the create_ras_terrain step succesfully. Note: I only tried this for a sample of 20 models.

@BradfordBates-NOAA Why would our VRT would have no data at places where USGS has data? Is it because we are processing some models that are outside of FIM 60 ?

**Comment by sclaw** [comment]
I have more time today, so I can make a map of areas where the DEMS are nodata

**Comment by sclaw** [comment]
It appears that all the nodata rasters are in the PNW.  

![image](https://github.com/user-attachments/assets/f171d8aa-5b90-45df-899e-1f2d3f3d0d96)

[null_terrain.zip](https://github.com/user-attachments/files/18282073/null_terrain.zip)

**Comment by sclaw** [comment]
FYSA, I opened #281 for this.

**Comment by ar-siddiqui** [comment]
> It appears that all the nodata rasters are in the PNW.
> 
> ![image](https://private-user-images.githubusercontent.com/90214958/399485829-f171d8aa-5b90-45df-899e-1f2d3f3d0d96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzMyNzEsIm5iZiI6MTczNTY3Mjk3MSwicGF0aCI6Ii85MDIxNDk1OC8zOTk0ODU4MjktZjE3MWQ4YWEtNWI5MC00NWRmLTg5OWUtMWYyZDNmM2QwZDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE5MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YzNlOWU3MzE3ZmMzM2JlYmI5NDE0NDI0NjBkMGU1Y2Y3MjI5OWNhZGJlYTY2NjgzNGI3Y2E1YzFhYWM4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kx4VhamZnYswI05vgr43xOZcPtEfsw5c69ZSQ9vGRYg)
> 
> [null_terrain.zip](https://github.com/user-attachments/files/18282073/null_terrain.zip)
> 
> And for what it's worth, here are the terrain metrics that result from a nodata raster. Currently, the terrain metrics run after the generate terrain step that causes this error, but we could move it before that step and use the metrics to catch this error and raise a more informative one.
> 
> ![terrain_metrics](https://private-user-images.githubusercontent.com/90214958/399488971-1f50211d-eba0-4a0d-a765-d2f4df29dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzMyNzEsIm5iZiI6MTczNTY3Mjk3MSwicGF0aCI6Ii85MDIxNDk1OC8zOTk0ODg5NzEtMWY1MDIxMWQtZWJhMC00YTBkLWE3NjUtZDJmNGRmMjlkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE5MjI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4M2ZiYjU4MThjNjEzZjE4MDcyMmJkY2Y5OTA0YTM4ODEzZjczOTExNmIxNTY1MDQ5YjIxMTYxMGYyMTRhZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hEl7NFWOl_p2RpGkHGX33w4ErsEn7mTgqLGFyLtM9nU)

Terrain metrics after terrain is created make more sense. #281 is what we need though.

**Comment by sclaw** [comment]
#282 has been opened for error Rank 4.

**Comment by sclaw** [comment]
Rank 5 should be addressed with #275

**Comment by sclaw** [comment]
Opened #291 for Rank 6

Opened #292 for Rank 8

**Comment by sclaw** [comment]
Rank 7 comes largely from two types of errors.  

![image](https://github.com/user-attachments/assets/9de3d244-3ef5-4bfc-a2c5-fca4d57f8d61)

304 of the occurrences are due to long-running models.  For these models, the normal depth run had not completed by the time the run_kwse endpoint was called.  

357 of the occurrences appeared to have the same failure pattern.

On re-running those 357 models, 345 of the errors were due to the issue of null downstream reach lengths shown in Rank 8.  These should be addressed by #292.  The other 12 errors could not be reproduced, and the models ran fine.

**Comment by sclaw** [comment]
304 of the Rank 9 errors were present in Rank 7.  All Rank 9 errors appear to stem from long-running models and models with 'unknown' status for the first nd run.

![image](https://github.com/user-attachments/assets/528e44b3-3363-41da-80fb-ecb5c6b927d0)

**Comment by sclaw** [comment]
75% of Rank 10 errors were caused by the downstream xs river station being higher valued than the upstream xs river station.  I still think #294 is the correct fix for this.
